# Generated by Django 5.2.14 on 2026-07-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_businessupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesslisting",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a wide image that represents your business.",
                null=True,
                upload_to="businesses/hero_images/",
                verbose_name="Business hero image",
            ),
        ),
        migrations.AlterField(
            model_name="businesslisting",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
