# Generated by Django 5.2.14 on 2026-07-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_businesslisting_hero_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessupdate",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Show this update at the top of the business page.",
            ),
        ),
    ]
