# Generated by Django 5.2.14 on 2026-07-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_businessupdate_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image")], default="image", max_length=20
                    ),
                ),
                ("image", models.ImageField(upload_to="businesses/media/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="businesses.businesslisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Media",
                "verbose_name_plural": "Business Media",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
