# Generated by Django 5.2.14 on 2026-07-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0006_businessmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessupdate",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this update becomes publicly visible.",
                null=True,
            ),
        ),
    ]
