# Generated by Django 5.2.14 on 2026-08-01 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0056_auction_hashtags"),
        ("businesses", "0007_businessupdate_scheduled_for"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="businesslisting",
            name="is_imported",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="businesslisting",
            name="last_imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesslisting",
            name="source_external_id",
            field=models.CharField(
                blank=True,
                help_text="Business identifier assigned by the external source.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="businesslisting",
            name="source_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Name of the external source that supplied this listing.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="businesslisting",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Original public source URL for this listing."
            ),
        ),
        migrations.AddConstraint(
            model_name="businesslisting",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_name__gt", ""), ("source_external_id__gt", "")
                ),
                fields=("source_name", "source_external_id"),
                name="unique_business_external_source",
            ),
        ),
    ]
