# Generated by Django 5.2.14 on 2026-08-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0008_businesslisting_is_imported_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesslisting",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Full public street address for this business.",
                max_length=500,
            ),
        ),
    ]
