# Generated by Django 5.2.14 on 2026-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_businesslisting_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesslisting",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Original public source URL for this listing.",
                max_length=1000,
            ),
        ),
    ]
