# Generated by Django 5.2.14 on 2026-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0010_alter_businesslisting_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesslisting",
            name="is_community",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marks this listing as a reusable community business template.",
            ),
        ),
    ]
