# Generated by Django 5.2.14 on 2026-08-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0011_businesslisting_is_community"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesslisting",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
