from django.contrib.auth import get_user_model
from .models import Notification, Conversation, DirectMessage
from datetime import timedelta
import re
import requests
from django.db.models import BooleanField, Exists, OuterRef, Subquery, Value
from django.db import transaction
from django.utils import timezone
from django.utils.html import strip_tags
from django.core.exceptions import ValidationError
from decimal import Decimal
from django.core.mail import send_mail
from django.conf import settings
from .models import Auction, Bid
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from .utils import get_system_wallet

from .models import (
    BidWallet,
    CreditPurchase,
    WalletTransaction,
    CreditPackage,
)

def translate_direct_message_for_language(
    message,
    language="en",
):
    """
    Return a display translation for a human DirectMessage.

    The original message body is never modified.
    Translations are cached in message.translations by target language.
    """
    language = (
        language or "en"
    ).lower().split("-")[0]

    if language not in {"en", "es", "pt"}:
        language = "en"

    original_language = (
        message.original_language or ""
    ).lower().split("-")[0]

    body = message.body or ""

    # AI/system messages are already generated for their intended context.
    # Phase 10 v1 translates only user-authored human messages.
    if message.message_type != DirectMessage.HUMAN:
        return body

    # Legacy DirectMessage rows predate Phase 10 source-language tracking.
    # Leave them untouched rather than guessing whether they were authored
    # by a human or generated by an older automated workflow.
    if not original_language:
        return body

    if not body.strip():
        return body

    if original_language and original_language == language:
        return body

    cached = (message.translations or {}).get(language)

    if cached:
        return cached

    language_names = {
        "en": "English",
        "es": "Spanish",
        "pt": "Portuguese",
    }

    target_language = language_names[language]

    source_instruction = ""
    if original_language in language_names:
        source_instruction = (
            f"The source language is "
            f"{language_names[original_language]}.\n"
        )

    prompt = f"""
You are a precise translation engine for FANZ direct messages.

{source_instruction}Translate the message into {target_language}.

Rules:
- Preserve the sender's meaning and tone.
- Translate naturally, not word-for-word when that sounds awkward.
- Preserve usernames, @mentions, hashtags, URLs, emojis, numbers,
  wallet codes, product names, and proper names.
- Do not explain the translation.
- Do not add information.
- Return ONLY the translated message.

Message:
{body}
"""

    try:
        response = requests.post(
            "http://172.17.0.1:11434/api/generate",

            json={
                "model": "gemma3:latest",
                "prompt": prompt,
                "stream": False,
                "options": {
                    "num_predict": 500,
                },
            },
            timeout=45,
        )

        response.raise_for_status()

        translated = (
            response.json()
            .get("response", "")
            .strip()
        )

        if not translated:
            return body

        translations = dict(message.translations or {})
        translations[language] = translated

        message.translations = translations
        message.save(update_fields=["translations"])

        return translated

    except Exception as e:
        print(
            "DM_TRANSLATION_FAILED",
            f"| message_id={message.id}",
            f"| source={original_language or 'unknown'}",
            f"| target={language}",
            f"| error={e}",
        )

        # Translation failure must never block the DM thread.
        return body


def localize_notification_message(
    notification,
    language="en",
):
    """
    Return a localized display message for a Notification.

    Notification.message remains the canonical stored message.
    Localization happens at display time so changing EN / ES / PT
    immediately changes notification presentation.
    """
    language = (
        language or "en"
    ).lower().split("-")[0]

    if language not in {
        "en",
        "es",
        "pt",
    }:
        language = "en"

    message = notification.message or ""

    if language == "en":
        return message

    actor_username = (
        notification.actor.username
        if notification.actor
        else ""
    )

    notification_type = (
        notification.notification_type
    )

    # TIP notifications need variable data such as the credit amount.
    # New notifications store this in metadata. Older notifications
    # fall back to parsing the canonical English message.
    if notification_type == Notification.TIP:
        metadata = notification.metadata or {}
        action = metadata.get("action")
        amount = metadata.get("amount")

        if action not in {"sent", "tipped"} or amount is None:
            match = re.search(
                r"\b(sent you|tipped you)\s+(\d+)\s+credits\b",
                message,
                re.IGNORECASE,
            )

            if match:
                action = (
                    "sent"
                    if match.group(1).lower() == "sent you"
                    else "tipped"
                )
                amount = int(match.group(2))

        if action in {"sent", "tipped"} and amount is not None:
            if language == "es":
                if action == "sent":
                    return (
                        f"💰 {actor_username} te envió "
                        f"{amount} créditos."
                    )

                return (
                    f"💰 {actor_username} te dio una propina de "
                    f"{amount} créditos."
                )

            if language == "pt":
                if action == "sent":
                    return (
                        f"💰 {actor_username} enviou "
                        f"{amount} créditos para você."
                    )

                return (
                    f"💰 {actor_username} deu uma gorjeta de "
                    f"{amount} créditos para você."
                )

    # UNLOCK notifications include the purchase price and creator earnings.
    # New notifications use structured metadata; older notifications fall
    # back to parsing the canonical English message.
    if notification_type == Notification.UNLOCK:
        metadata = notification.metadata or {}
        price = metadata.get("price")
        creator_amount = metadata.get("creator_amount")

        if price is None or creator_amount is None:
            match = re.search(
                r"unlocked your premium post for\s+(\d+)\s+credits\.\s+"
                r"You earned\s+(\d+)\s+credits\.",
                message,
                re.IGNORECASE,
            )

            if match:
                price = int(match.group(1))
                creator_amount = int(match.group(2))

        if price is not None and creator_amount is not None:
            if language == "es":
                return (
                    f"🔓 {actor_username} desbloqueó tu publicación premium "
                    f"por {price} créditos. Ganaste {creator_amount} créditos."
                )

            if language == "pt":
                return (
                    f"🔓 {actor_username} desbloqueou sua publicação premium "
                    f"por {price} créditos. Você ganhou "
                    f"{creator_amount} créditos."
                )

    # MESSAGE notifications cover several different behaviors.
    # Structured metadata lets us localize known message kinds safely
    # while leaving unrelated MESSAGE notifications unchanged.
    if notification_type == Notification.MESSAGE:
        metadata = notification.metadata or {}
        kind = metadata.get("kind")

        if kind == "direct_message":
            count = notification.count or 1

            if language == "es":
                if count == 1:
                    return (
                        f"📩 @{actor_username} te envió un mensaje"
                    )

                return (
                    f"📩 @{actor_username} te envió "
                    f"{count} mensajes"
                )

            if language == "pt":
                if count == 1:
                    return (
                        f"📩 @{actor_username} enviou uma mensagem para você"
                    )

                return (
                    f"📩 @{actor_username} enviou "
                    f"{count} mensagens para você"
                )

        if kind == "sender_reward":
            event_type = metadata.get("event_type")

            reward_messages = {
                "es": {
                    "like":
                        f"@{actor_username}: Gracias por el ❤️",
                    "tip":
                        f"@{actor_username}: Gracias por los créditos ❤️",
                    "unlock":
                        f"@{actor_username}: Gracias por desbloquear mi publicación 🔓",
                    "fan":
                        f"@{actor_username}: Bienvenido a mis Fanz ⭐",
                },
                "pt": {
                    "like":
                        f"@{actor_username}: Obrigado pelo ❤️",
                    "tip":
                        f"@{actor_username}: Obrigado pelos créditos ❤️",
                    "unlock":
                        f"@{actor_username}: Obrigado por desbloquear minha publicação 🔓",
                    "fan":
                        f"@{actor_username}: Bem-vindo aos meus Fanz ⭐",
                },
            }

            localized_reward = (
                reward_messages
                .get(language, {})
                .get(event_type)
            )

            if localized_reward:
                return localized_reward

    # AUCTION notifications use structured metadata for winner,
    # purchase-complete, and outbid events.
    if notification_type == Notification.AUCTION:
        metadata = notification.metadata or {}
        kind = metadata.get("kind")
        auction_title = metadata.get("auction_title")

        if kind and auction_title:
            if language == "es":
                if kind == "winner":
                    return (
                        f"🏆 ¡Eres el ganador!\n\n"
                        f"{auction_title}\n\n"
                        f"Enlace de descarga disponible."
                    )

                if kind == "purchase_complete":
                    return (
                        f"🎉 ¡Compra completada!\n\n"
                        f"{auction_title}\n\n"
                        f"Enlace de descarga disponible."
                    )

                if kind == "outbid":
                    return (
                        f"📣 ¡Han superado tu oferta!\n"
                        f"{auction_title}\n"
                        f"Toca para volver a ofertar."
                    )

            if language == "pt":
                if kind == "winner":
                    return (
                        f"🏆 Você é o vencedor!\n\n"
                        f"{auction_title}\n\n"
                        f"Link para download disponível."
                    )

                if kind == "purchase_complete":
                    return (
                        f"🎉 Compra concluída!\n\n"
                        f"{auction_title}\n\n"
                        f"Link para download disponível."
                    )

                if kind == "outbid":
                    return (
                        f"📣 Sua oferta foi superada!\n"
                        f"{auction_title}\n"
                        f"Toque para dar outro lance."
                    )

    translations = {
        "es": {
            Notification.LIKE:
                f"❤️ {actor_username} indicó que le gusta tu publicación.",

            Notification.COMMENT:
                f"💬 {actor_username} comentó en tu publicación.",

            Notification.FAN:
                f"⭐ {actor_username} se ha convertido en uno de tus Fanz!",

            Notification.TIP:
                None,

            Notification.UNLOCK:
                None,

            Notification.MESSAGE:
                None,

            Notification.AUCTION:
                None,
        },

        "pt": {
            Notification.LIKE:
                f"❤️ {actor_username} curtiu sua publicação.",

            Notification.COMMENT:
                f"💬 {actor_username} comentou na sua publicação.",

            Notification.FAN:
                f"⭐ {actor_username} se tornou um dos seus Fanz!",

            Notification.TIP:
                None,

            Notification.UNLOCK:
                None,

            Notification.MESSAGE:
                None,

            Notification.AUCTION:
                None,
        },
    }

    localized = (
        translations
        .get(language, {})
        .get(notification_type)
    )

    if localized:
        return localized

    return message

def send_winner_email(auction):
    if not auction.winner or not auction.winner.email:
        return

    delivery_url = ""

    if auction.digital_item and auction.digital_item.delivery_url:
        delivery_url = auction.digital_item.delivery_url

    html_content = render_to_string(
        "emails/auction_winner.html",
        {
            "user": auction.winner,
            "auction": auction,
            "delivery_url": delivery_url,
            "site_url": "https://fanz.to",
        },
    )

    text_content = strip_tags(html_content)

    email = EmailMultiAlternatives(
        subject=f"🎉 You Won: {auction.title}",
        body=text_content,
        to=[auction.winner.email],
    )

    email.attach_alternative(html_content, "text/html")
    email.send()

def send_digital_delivery_message(user, auction, event_type="buy_now"):
    User = get_user_model()
    platform_sender = User.objects.get(username="platform")

    delivery_link = ""
    if auction.digital_item and auction.digital_item.delivery_url:
        delivery_link = (
            f"\n\n📦 Download your item:\n"
            f"{auction.digital_item.delivery_url}"
        )

    if event_type == "auction_win":
        notification_message = (
            f"🏆 You're a Winner!\n\n{auction.title}\n\nDownload link inside."
        )
        dm_body = f"🎉 You're a Winner!\n\n{auction.title}!{delivery_link}"
    else:
        notification_message = (
            f"🎉 Purchase Complete!\n\n{auction.title}\n\nDownload link inside."
        )
        dm_body = f"🎉 Purchase Complete!\n\n{auction.title}!{delivery_link}"

    Notification.objects.create(
        user=user,
        actor=None,
        notification_type=Notification.AUCTION,
        message=notification_message,
        metadata={
            "kind": (
                "winner"
                if event_type == "auction_win"
                else "purchase_complete"
            ),
            "auction_title": auction.title,
        },
    )

    conversation = Conversation.objects.create()
    conversation.participants.add(platform_sender, user)

    DirectMessage.objects.create(
        conversation=conversation,
        sender=platform_sender,
        body=dm_body,
        message_type=DirectMessage.SYSTEM,
    )


@transaction.atomic
def place_bid(auction_id, user):
    auction = Auction.objects.select_for_update().get(id=auction_id)
    wallet = BidWallet.objects.select_for_update().get(user=user)

    previous_bid = auction.bids.order_by("-created_at").first()
    now = timezone.now()

    if auction.status != "live":
        raise ValidationError("Auction is not live.")

    if not (auction.starts_at <= now < auction.ends_at):
        raise ValidationError("Auction not active.")

    if wallet.credits <= 0:
        raise ValidationError("No credits remaining.")

    platform_wallet = get_system_wallet()

    wallet.credits -= 1
    platform_wallet.credits += 1

    wallet.save(update_fields=["credits"])
    platform_wallet.save(update_fields=["credits"])

    new_price = auction.current_price + auction.bid_increment

    Bid.objects.create(
        auction=auction,
        user=user,
        amount=new_price,
    )

    WalletTransaction.objects.create(
        sender=wallet,
        receiver=platform_wallet,
        amount=1,
        transaction_type="game",
        reference=f"Bid on auction #{auction.id}: {auction.title}",
)

    auction.current_price = new_price

    if (auction.ends_at - now) <= timedelta(seconds=45):
        auction.ends_at += timedelta(seconds=15)

    auction.save(update_fields=["current_price", "ends_at"])

    if previous_bid and previous_bid.user != user and previous_bid.user.email:


        auction_url = f"https://fanz.to/auctions/{auction.id}/"

        context = {
                "user": previous_bid.user,
                "auction": auction,
                "auction_url": auction_url,
        }

        text_body = render_to_string("emails/outbid.txt", context)
        html_body = render_to_string("emails/outbid.html", context)

        email = EmailMultiAlternatives(
            subject=f"You were outbid on {auction.title}",
            body=text_body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            to=[previous_bid.user.email],
        )
        email.attach_alternative(html_body, "text/html")
        email.send(fail_silently=False)

        Notification.objects.create(
            user=previous_bid.user,
            actor=user,
            notification_type=Notification.AUCTION,
            message=(
                f"📣 You Were Outbid!\n"
                f"{auction.title}\n"
                f"Tap to bid again."
            ),
            metadata={
                "kind": "outbid",
                "auction_title": auction.title,
            },
        )

        User = get_user_model()
        platform_sender = User.objects.get(username="platform")

        conversation = Conversation.objects.create()
        conversation.participants.add(platform_sender, previous_bid.user)

        DirectMessage.objects.create(
            conversation=conversation,
            sender=platform_sender,
            body=(
                f"😡 You were outbid!\n\n"
                f"{auction.title}.\n\n"
                f"Bid again here:\n"
                f"{auction_url}"
            ),
            message_type=DirectMessage.SYSTEM,
        )

    return auction


@transaction.atomic
def close_auction(auction_id):
    auction = Auction.objects.select_for_update().get(id=auction_id)

    if auction.status == "ended":
        return auction

    now = timezone.now()

    if now < auction.ends_at:
        raise ValidationError("Auction has not ended yet.")

    last_bid = auction.bids.order_by("-created_at").first()

    if last_bid:
        auction.winner = last_bid.user

    auction.status = "ended"
    auction.save(update_fields=["status", "winner"])

    if auction.winner and not auction.winner_email_sent:
        send_winner_email(auction)

        send_digital_delivery_message(
            user=auction.winner,
            auction=auction,
            event_type="auction_win",
        )

        auction.winner_email_sent = True
        auction.save(update_fields=["winner_email_sent"])

    return auction


def prepare_auction_cards(
    auctions,
    user,
    now=None,
    language=None,
):
    """
    Prepare auctions for reusable card rendering.

    Adds countdown, favorite, and high-bidder presentation data
    without issuing separate queries for every auction.
    """
    from django.utils import timezone

    from .models import Bid, FavoriteAuction

    if now is None:
        now = timezone.now()

    latest_bid_user = (
        Bid.objects
        .filter(auction_id=OuterRef("pk"))
        .order_by("-created_at")
        .values("user_id")[:1]
    )

    auctions = auctions.annotate(
        last_bid_user_id=Subquery(latest_bid_user),
    )

    if user.is_authenticated:
        favorite = FavoriteAuction.objects.filter(
            user=user,
            auction_id=OuterRef("pk"),
        )

        auctions = auctions.annotate(
            is_favorited=Exists(favorite),
        )
    else:
        auctions = auctions.annotate(
            is_favorited=Value(
                False,
                output_field=BooleanField(),
            ),
        )
    if language:
        language = str(language).lower().split("-")[0]

        if language not in ("en", "es", "pt"):
            language = "en"

        auctions = auctions.prefetch_related(
            "translations",
        )
    prepared_auctions = list(auctions)

    for auction in prepared_auctions:
        remaining = (
            auction.ends_at - now
        ).total_seconds()
        auction.seconds_remaining = max(
            0,
            int(remaining),
        )
        auction.is_high_bidder = bool(
            user.is_authenticated
            and auction.last_bid_user_id == user.id
        )

        # Canonical fallbacks.
        auction.display_title = auction.title
        auction.display_description = ""
        auction.localized_hero_image = None

        if language:
            translation = next(
                (
                    item
                    for item in auction.translations.all()
                    if item.language == language
                ),
                None,
            )

            if translation:
                if translation.title:
                     auction.display_title = translation.title

                if translation.description:
                    auction.display_description = (
                        translation.description
                    )

                if (
                    translation.use_language_hero
                    and translation.hero_image
                ):
                    auction.localized_hero_image = (
                        translation.hero_image
                    )
    return prepared_auctions


def prepare_feed_posts(posts, language=None):
    """
    Prepare feed posts for localized presentation.

    Adds display_title and display_content while preserving
    canonical post fields as fallbacks.
    """

    if language:
        language = str(language).lower().split("-")[0]

        if language not in ("en", "es", "pt"):
            language = "en"

        posts = posts.prefetch_related("translations")

    prepared_posts = list(posts)

    for post in prepared_posts:
        post.display_title = post.title
        post.display_content = post.content

        if language:
            translation = next(
                (
                    item
                    for item in post.translations.all()
                    if item.language == language
                ),
                None,
            )

            if translation:
                if translation.title:
                    post.display_title = translation.title

                if translation.content:
                    post.display_content = translation.content

    return prepared_posts


def calculate_node_commission(node, package):
    """
    Returns commission amount in USD based on package price.
    """
    if not node or not node.commission_rate:
        return Decimal("0.00")

    return (package.price_usd * node.commission_rate).quantize(Decimal("0.01"))


def calculate_node_commission(node, package):
    if not node or not node.commission_rate:
        return Decimal("0.00")

    return (package.price_usd * node.commission_rate).quantize(Decimal("0.01"))


@transaction.atomic
def process_credit_purchase(*, user, package, external_id, source_node=None):
    """
    Safely processes a credit purchase.

    Rules:
    - external_id prevents duplicate purchases
    - credits user wallet
    - logs purchase
    - calculates node commission if source_node exists
    """

    if CreditPurchase.objects.filter(external_id=external_id).exists():
        return CreditPurchase.objects.get(external_id=external_id), False

    wallet, _ = BidWallet.objects.select_for_update().get_or_create(user=user)

    purchase = CreditPurchase.objects.create(
        user=user,
        wallet=wallet,
        package=package,
        amount_paid=package.price_usd,
        external_id=external_id,
        source_type="node" if source_node else "direct",
        source_node=source_node,
    )


    commission_amount = calculate_node_commission(source_node, package)

    if source_node and commission_amount > 0:
        node_wallet, _ = BidWallet.objects.select_for_update().get_or_create(
            user=source_node.user
    )

    # Current simple rule:
    # $1 commission = 1 platform credit
        commission_credits = int(package.credits * source_node.commission_rate)

        if commission_credits > 0:
            node_wallet.credits += commission_credits
            node_wallet.save()

            WalletTransaction.objects.create(
                sender=node_wallet,
                receiver=node_wallet,
                amount=commission_credits,
                transaction_type="commission",
                reference=f"Commission:{purchase.id}",
                )

    wallet.credits += package.credits
    wallet.save()

    WalletTransaction.objects.create(
        sender=wallet,
        receiver=wallet,
        amount=package.credits,
        transaction_type="purchase",
        reference=f"Purchase:{purchase.id}",
     )

    commission_amount = calculate_node_commission(source_node, package)

    # We calculate this now, but do NOT mint commission credits yet
    # until we decide whether commission is paid in USD or credits.

    return purchase, True


def _get_public_hashtag_post_queryset(hashtag):
    """
    Build the shared queryset for public, free hashtag posts eligible
    for public Discovery surfaces.

    Keep Discovery eligibility rules here so listing and metric
    capabilities cannot drift apart.
    """
    from django.db.models import Count, Q

    from .models import FeedPost, FeedPostMedia

    return (
        FeedPost.objects
        .filter(
            hashtags=hashtag,
            is_public=True,
            is_paid=False,
        )
        .annotate(
            active_image_count=Count(
                "media",
                filter=Q(
                    media__is_active=True,
                    media__media_type=FeedPostMedia.MEDIA_TYPE_IMAGE,
                ),
                distinct=True,
            ),
            forbidden_media_count=Count(
                "media",
                filter=Q(
                    media__is_active=True,
                    media__media_type__in=[
                        FeedPostMedia.MEDIA_TYPE_VIDEO,
                        FeedPostMedia.MEDIA_TYPE_AUDIO,
                        FeedPostMedia.MEDIA_TYPE_PDF,
                    ],
                ),
                distinct=True,
            ),
        )
        .filter(
            forbidden_media_count=0,
            active_image_count__lte=3,
        )
        .filter(
            Q(active_image_count__gte=1)
            |
            (
                Q(image__isnull=False)
                & ~Q(image="")
            )
        )
    )


def get_public_hashtag_posts(hashtag, limit=None):
    """
    Return public, free hashtag posts eligible for public discovery surfaces.

    This queryset is shared by hashtag feeds, Discovery Hubs, and future
    search, syndication, API, and AI consumers.
    """
    queryset = (
        _get_public_hashtag_post_queryset(hashtag)
        .select_related(
            "user",
            "user__profile",
            "user__bidwallet",
        )
        .prefetch_related(
            "media",
            "hashtags",
            "likes",
        )
        .order_by("-created_at")
    )

    if limit is not None:
        queryset = queryset[:limit]

    return queryset


def get_public_hashtag_post_count(hashtag):
    """
    Return the total number of public, free hashtag posts eligible
    for public Discovery surfaces.
    """
    return _get_public_hashtag_post_queryset(hashtag).count()
