# Generated by Django 5.2.14 on 2026-05-09 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_force_wallet_tx'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('affiliate', 'Affiliate Host'), ('sales', 'Sales Node Operator'), ('validator', 'Validator Node Operator')], default='affiliate', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('node_name', models.CharField(blank=True, max_length=120)),
                ('node_slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('node_domain', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('validator_public_key', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
