# Generated by Django 5.2.14 on 2026-05-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_add_node_profile_only'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE auctions_bidwallet
                ADD COLUMN IF NOT EXISTS source_node_id bigint NULL;

                ALTER TABLE auctions_bidwallet
                ADD CONSTRAINT auctions_bidwallet_source_node_id_fk
                FOREIGN KEY (source_node_id)
                REFERENCES auctions_nodeprofile(id)
                DEFERRABLE INITIALLY DEFERRED;

                CREATE INDEX IF NOT EXISTS auctions_bidwallet_source_node_id_idx
                ON auctions_bidwallet(source_node_id);
            """,
            reverse_sql="""
                ALTER TABLE auctions_bidwallet
                DROP CONSTRAINT IF EXISTS auctions_bidwallet_source_node_id_fk;

                DROP INDEX IF EXISTS auctions_bidwallet_source_node_id_idx;

                ALTER TABLE auctions_bidwallet
                DROP COLUMN IF EXISTS source_node_id;
            """,
        ),
    ]
