# Generated by Django 5.2.14 on 2026-05-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_creditpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("transfer", "Transfer"),
                    ("purchase", "Purchase"),
                    ("commission", "Commission"),
                    ("bonus", "Bonus"),
                    ("game", "Game"),
                ],
                default="transfer",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="reference",
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
    ]
