# Generated by Django 5.2.14 on 2026-05-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20260509_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='auctions.bidwallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='auctions.bidwallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('purchase', 'Purchase'), ('commission', 'Commission'), ('bonus', 'Bonus'), ('game', 'Game'), ('ai_message', 'AI Message')], max_length=20),
        ),
    ]
