# Generated by Django 5.2.14 on 2026-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_aicompanion_aiconversation_aimessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aicompanion',
            name='provider',
            field=models.CharField(choices=[('local_ollama', 'Local Ollama'), ('local_deepseek', 'Local DeepSeek'), ('openai', 'OpenAI Deluxe')], default='local_deepseek', max_length=30),
        ),
    ]
