# Generated by Django 5.2.14 on 2026-05-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_aiconversation_is_pinned_alter_aicompanion_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='reminder_60_sent',
            field=models.BooleanField(default=False),
        ),
    ]
