# Generated by Django 5.2.14 on 2026-05-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_reminder_60_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
