# Generated by Django 5.2.14 on 2026-05-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auction_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicompanion',
            name='prompt_key',
            field=models.CharField(default='flirty_social', max_length=50),
        ),
    ]
