# Generated by Django 5.2.14 on 2026-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='unlock_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
