# Generated by Django 5.2.14 on 2026-06-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_feedpost_is_pinned_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banners/'),
        ),
    ]
