# Generated by Django 5.2.14 on 2026-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_userprofile_instagram_userprofile_is_official_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
