# Generated by Django 5.2.14 on 2026-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('fan', 'Fan'), ('tip', 'Tip'), ('unlock', 'Unlock'), ('auction', 'Auction')], default='fan', max_length=20),
        ),
    ]
