# Generated by Django 5.2.14 on 2026-06-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('fan', 'Fan'), ('tip', 'Tip'), ('unlock', 'Unlock'), ('auction', 'Auction'), ('like', 'Like'), ('comment', 'Comment')], default='fan', max_length=20),
        ),
    ]
