# Generated by Django 5.2.14 on 2026-06-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('tip', 'Tip'), ('unlock', 'Premium Unlock'), ('purchase', 'Purchase'), ('commission', 'Commission'), ('bonus', 'Bonus'), ('game', 'Game'), ('ai_message', 'AI Message')], max_length=20),
        ),
    ]
