# Generated by Django 5.2.14 on 2026-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_notification_notification_type_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
