# Generated by Django 5.2.14 on 2026-06-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_feedpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ai_creator',
            field=models.BooleanField(default=False),
        ),
    ]
