# Generated by Django 5.2.14 on 2026-06-20 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_userprofile_is_ai_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICreatorMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_status', models.BooleanField(default=False)),
                ('total_tips', models.PositiveIntegerField(default=0)),
                ('total_unlocks', models.PositiveIntegerField(default=0)),
                ('total_tip_credits', models.PositiveIntegerField(default=0)),
                ('total_unlock_credits', models.PositiveIntegerField(default=0)),
                ('first_contact_date', models.DateTimeField(auto_now_add=True)),
                ('last_contact_date', models.DateTimeField(auto_now=True)),
                ('conversation_count', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_creator_memories', to=settings.AUTH_USER_MODEL)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_fan_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_contact_date'],
                'unique_together': {('creator', 'fan')},
            },
        ),
    ]
