# Generated by Django 5.2.14 on 2026-06-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_aifanmemorynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ai_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
