# Generated by Django 5.2.14 on 2026-06-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_userprofile_is_ai_influencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_by_ai', models.BooleanField(default=False)),
            ],
        ),
    ]
