# Generated by Django 5.2.14 on 2026-06-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_dmmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DMMessage',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
