# Generated by Django 5.2.14 on 2026-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_alter_notification_options_notification_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sound_type', models.CharField(choices=[('cash', 'Cash / Ka-ching'), ('social', 'Social / Tink')], max_length=20)),
                ('file', models.FileField(upload_to='notification_sounds/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
