# Generated by Django 5.2.14 on 2026-07-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_discoveryhub'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryhub',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
