# Generated by Django 5.2.14 on 2026-07-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_discoveryhub_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryhub',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
