# Generated by Django 5.2.14 on 2026-07-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_alter_discoveryhub_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryHubTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='discovery_hubs/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('telegram_text', models.TextField(blank=True)),
                ('pinterest_text', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('ai_personality', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='auctions.discoveryhub')),
            ],
            options={
                'ordering': ['hub__sort_order', 'language'],
                'unique_together': {('hub', 'language')},
            },
        ),
    ]
