# Generated by Django 5.2.14 on 2026-07-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_discoveryhubtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryhubtranslation',
            name='template_name',
            field=models.CharField(blank=True, default='default', help_text='Template key for this localized Discovery Experience, e.g. default, restaurants, hotels, doctors.', max_length=100),
        ),
    ]
