# Generated by Django 5.2.14 on 2026-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0049_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_ai_influencer",
            field=models.BooleanField(
                default=False,
                help_text="Display the AI Influencer badge on the public profile.",
            ),
        ),
    ]
