# Generated by Django 5.2.14 on 2026-07-22 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0051_repair_event_type_column"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="feed/media/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="auctions.feedpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Post Media",
                "verbose_name_plural": "Feed Post Media",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
