# Generated by Django 5.2.14 on 2026-07-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0053_feedpostmedia_mixed_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="auctions/media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        db_index=True,
                        default="image",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="auctions.auction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction Media",
                "verbose_name_plural": "Auction Media",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
