# Generated by Django 5.2.14 on 2026-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0055_migrate_legacy_auction_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="auctions", to="auctions.hashtag"
            ),
        ),
    ]
