# Generated by Django 5.2.14 on 2026-08-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0056_auction_hashtags"),
        ("businesses", "0008_businesslisting_is_imported_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidwallet",
            name="pending_referral_business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_referral_wallets",
                to="businesses.businesslisting",
            ),
        ),
    ]
