# Generated by Django 5.2.14 on 2026-08-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0057_bidwallet_pending_referral_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveryhubtranslation",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish"), ("pt", "Portuguese")],
                max_length=10,
            ),
        ),
    ]
