# Generated by Django 5.2.14 on 2026-08-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0058_alter_discoveryhubtranslation_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("pt", "Portuguese"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="auction_translations/"
                    ),
                ),
                ("use_language_hero", models.BooleanField(default=False)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="auctions.auction",
                    ),
                ),
            ],
            options={
                "ordering": ["auction_id", "language"],
                "unique_together": {("auction", "language")},
            },
        ),
        migrations.CreateModel(
            name="DigitalItemTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("pt", "Portuguese"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="digital_item_translations/"
                    ),
                ),
                ("delivery_url", models.URLField(blank=True)),
                (
                    "digital_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="auctions.digitalitem",
                    ),
                ),
            ],
            options={
                "ordering": ["digital_item_id", "language"],
                "unique_together": {("digital_item", "language")},
            },
        ),
    ]
