# Generated by Django 5.2.14 on 2026-08-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0059_auctiontranslation_digitalitemtranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("pt", "Portuguese"),
                        ],
                        max_length=2,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("bank_payment_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="auctions.userprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "language"),
                        name="unique_user_profile_translation_language",
                    )
                ],
            },
        ),
    ]
