# Generated by Django 5.2.14 on 2026-08-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0060_userprofiletranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPostTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("pt", "Portuguese"),
                        ],
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("content", models.TextField(blank=True, default="", max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="auctions.feedpost",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "language"),
                        name="unique_feed_post_translation_language",
                    )
                ],
            },
        ),
    ]
