# Generated by Django 5.2.14 on 2026-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0061_feedposttranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_platform_account",
            field=models.BooleanField(
                default=False, help_text="FANZ Platform Account."
            ),
        ),
    ]
