# Generated by Django 5.2.14 on 2026-08-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0062_userprofile_is_platform_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
