# Generated by Django 5.2.14 on 2026-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0063_notification_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="original_language",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
