# Generated by Django 5.2.14 on 2026-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0064_directmessage_original_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="message_type",
            field=models.CharField(
                choices=[("human", "Human"), ("ai", "AI"), ("system", "System")],
                default="human",
                max_length=10,
            ),
        ),
    ]
