# Generated by Django 5.2.14 on 2026-08-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0066_founderaccount_accountcontrol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="founderaccount",
            options={"ordering": ["handle_length", "handle"]},
        ),
        migrations.RenameField(
            model_name="founderaccount",
            old_name="original_handle",
            new_name="handle",
        ),
        migrations.RemoveField(
            model_name="founderaccount",
            name="user",
        ),
        migrations.AddField(
            model_name="founderaccount",
            name="current_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="founder_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="founderaccount",
            name="floor_price_credits",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="founderaccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("owned", "Owned"),
                    ("listed", "Listed"),
                    ("reserved", "Reserved"),
                    ("treasury", "FANZ Treasury"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="founderaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
