# Generated by Django 5.2.14 on 2026-08-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0067_alter_founderaccount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founderaccount",
            name="handle_length",
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
