# Generated by Django 5.2.14 on 2026-08-17 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0068_alter_founderaccount_handle_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="founderaccount",
            name="owner_root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_founder_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
