# Generated by Django 5.2.14 on 2026-08-17 07:02

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0069_founderaccount_owner_root"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderLedgerHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="founder", editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "last_sequence",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "last_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FounderOwnershipLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveBigIntegerField(editable=False, unique=True),
                ),
                ("handle_snapshot", models.CharField(editable=False, max_length=4)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("p2p_fixed", "P2P Fixed Price"),
                            ("p2p_blind", "P2P Blind Sale"),
                            ("minimum_conveyance", "Minimum Founder Conveyance"),
                            ("treasury_release", "FANZ Treasury Release"),
                            ("cb_redemption", "FANZ CB Redemption"),
                        ],
                        default="minimum_conveyance",
                        max_length=32,
                    ),
                ),
                ("sale_price_credits", models.PositiveBigIntegerField()),
                ("platform_fee_credits", models.PositiveBigIntegerField()),
                ("seller_proceeds_credits", models.PositiveBigIntegerField()),
                ("wallet_transaction_ids", models.JSONField(blank=True, default=list)),
                ("previous_hash", models.CharField(editable=False, max_length=64)),
                (
                    "record_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer_root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_ledger_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "founder_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership_ledger",
                        to="auctions.founderaccount",
                    ),
                ),
                (
                    "seller_root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_ledger_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sale_price_credits__gte", 200)),
                        name="founder_ledger_minimum_200_credit_conveyance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "sale_price_credits",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("platform_fee_credits"),
                                    "+",
                                    models.F("seller_proceeds_credits"),
                                ),
                            )
                        ),
                        name="founder_ledger_settlement_balances",
                    ),
                ],
            },
        ),
    ]
