# Generated by Django 5.2.14 on 2026-08-18 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0070_founderledgerhead_founderownershipledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Price"), ("blind", "Blind Sale")],
                        max_length=16,
                    ),
                ),
                (
                    "fixed_price_credits",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "minimum_bid_credits",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "founder_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="auctions.founderaccount",
                    ),
                ),
                (
                    "seller_root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("founder_account",),
                        name="unique_active_founder_listing_per_asset",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("fixed_price_credits__gte", 200),
                                ("sale_type", "fixed"),
                            ),
                            models.Q(
                                ("minimum_bid_credits__gte", 200),
                                ("sale_type", "blind"),
                            ),
                            _connector="OR",
                        ),
                        name="founder_listing_minimum_200_credits",
                    ),
                ],
            },
        ),
    ]
