# Generated by Django 5.2.14 on 2026-08-18 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0071_founderlisting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="founderlisting",
            name="listing_source",
            field=models.CharField(
                choices=[("p2p", "P2P Marketplace"), ("tienda", "Founder Tienda")],
                default="p2p",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="founderlisting",
            name="tienda_lane",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed Price"),
                    ("blind", "Blind Offer"),
                    ("swamp", "Swamp Land"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="founderlisting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("listing_source", "p2p"), ("tienda_lane__isnull", True)),
                    models.Q(
                        ("listing_source", "tienda"), ("tienda_lane__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="founder_listing_tienda_lane_matches_source",
            ),
        ),
    ]
