# Generated by Django 5.2.14 on 2026-08-18 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0072_founderlisting_listing_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="founderlisting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tienda_lane", "swamp"), _negated=True),
                    models.Q(("fixed_price_credits", 200), ("sale_type", "fixed")),
                    _connector="OR",
                ),
                name="founder_tienda_swamp_exactly_200_fixed",
            ),
        ),
    ]
