# Generated by Django 5.2.14 on 2026-08-18 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0073_founderlisting_founder_tienda_swamp_exactly_200_fixed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_credits", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("outbid", "Outbid"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bidder_root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bids",
                        to="auctions.founderlisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-amount_credits", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FounderCreditHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_credits", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("released", "Released"),
                            ("consumed", "Consumed"),
                        ],
                        default="held",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_hold",
                        to="auctions.founderbid",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_credit_holds",
                        to="auctions.bidwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="founderbid",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("listing", "bidder_root"),
                name="unique_active_founder_bid_per_root_listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="founderbid",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_credits__gte", 200)),
                name="founder_bid_minimum_200_credits",
            ),
        ),
        migrations.AddConstraint(
            model_name="foundercredithold",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_credits__gte", 200)),
                name="founder_credit_hold_minimum_200_credits",
            ),
        ),
    ]
