# Generated by Django 5.2.14 on 2026-08-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0075_paymentintent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomyAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("symbol", models.CharField(max_length=16, unique=True)),
                ("chain", models.CharField(default="sui", max_length=16)),
                (
                    "coin_type",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("decimals", models.PositiveSmallIntegerField(default=6)),
                (
                    "genesis_supply_base_units",
                    models.PositiveBigIntegerField(default=21000000000000000),
                ),
                (
                    "genesis_tx_digest",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("supply_fixed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "founder_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="economy_asset",
                        to="auctions.founderaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["founder_account__handle"],
            },
        ),
        migrations.CreateModel(
            name="EconomyAssetDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_address", models.CharField(max_length=128)),
                ("amount_base_units", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitting", "Submitting"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "tx_digest",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="auctions.economyasset",
                    ),
                ),
                (
                    "payment_intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="economy_asset_delivery",
                        to="auctions.paymentintent",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_base_units__gt", 0)),
                        name="economy_asset_delivery_amount_positive",
                    )
                ],
            },
        ),
    ]
