# Generated by Django 5.2.14 on 2026-08-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0076_economyasset_economyassetdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentintent",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("integration_test", "Integration Test"),
                    ("credit_purchase", "Credit Purchase"),
                    ("donation", "Donation"),
                    ("founder_purchase", "Founder Purchase"),
                    ("platform_service", "Platform Service"),
                    ("economy_asset_purchase", "Economy Asset Purchase"),
                ],
                max_length=32,
            ),
        ),
    ]
