# Generated by Django 5.2.14 on 2026-08-26 23:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0077_alter_paymentintent_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="economyassetdelivery",
            name="sender_address",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="economyassetdelivery",
            name="submission_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="economyassetdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("prepared", "Prepared"),
                    ("submitted", "Submitted"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
