# Generated by Django 5.2.14 on 2026-08-29 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0078_economyassetdelivery_sender_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("checked_out", "Checked Out"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchaser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FounderCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wanted_handle", models.CharField(max_length=5)),
                ("budget_credits", models.PositiveBigIntegerField()),
                (
                    "list_price_credits",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "purchase_mode",
                    models.CharField(
                        choices=[("self", "For Me"), ("gift", "Send as Gift")],
                        default="self",
                        max_length=8,
                    ),
                ),
                ("sui_recipient_address", models.CharField(blank=True, max_length=128)),
                ("gift_recipient_name", models.CharField(blank=True, max_length=150)),
                ("gift_recipient_email", models.EmailField(blank=True, max_length=254)),
                ("gift_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("swamp_suggested", "Wasteland Suggested"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="auctions.foundercart",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cart", "wanted_handle"),
                        name="unique_founder_handle_per_cart",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("budget_credits__gt", 0)),
                        name="founder_cart_item_budget_positive",
                    ),
                ],
            },
        ),
    ]
