# Generated by Django 5.2.14 on 2026-08-29 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0079_foundercart_foundercartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="foundercartitem",
            name="price_memory_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foundercartitem",
            name="quoted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foundercartitem",
            name="reservation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foundercartitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("available", "Available"),
                    ("unavailable", "Unavailable"),
                    ("swamp_suggested", "Wasteland Suggested"),
                    ("quoted", "Quoted"),
                    ("purchased", "Purchased"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="FounderPriceMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wanted_handle", models.CharField(max_length=4)),
                ("list_price_credits", models.PositiveBigIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_price_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("buyer_root", "wanted_handle"),
                        name="unique_founder_price_memory_per_buyer_handle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("list_price_credits__gte", 200)),
                        name="founder_price_memory_minimum_200_credits",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FounderVendingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_credits", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("released", "Released"),
                            ("consumed", "Consumed"),
                        ],
                        default="held",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_hold",
                        to="auctions.foundercartitem",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founder_vending_holds",
                        to="auctions.bidwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_credits__gte", 200)),
                        name="founder_vending_hold_minimum_200_credits",
                    )
                ],
            },
        ),
    ]
