# Generated by Django 5.2.14 on 2026-08-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0080_foundercartitem_price_memory_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sui_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional public Sui wallet address used for Sui tips, donations, custom meme coins, and @4char vending.",
                max_length=66,
            ),
        ),
    ]
