# Generated by Django 5.2.14 on 2026-08-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0081_userprofile_sui_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="founderlisting",
            name="creator_coin_amount_base_units",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="founderlisting",
            name="creator_coin_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="founderlisting",
            name="creator_coin_seller_address",
            field=models.CharField(blank=True, default="", max_length=66),
        ),
        migrations.AddField(
            model_name="founderlisting",
            name="creator_coin_symbol_snapshot",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="founderlisting",
            name="creator_coin_type_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="founderlisting",
            name="include_creator_coin_balance",
            field=models.BooleanField(default=False),
        ),
    ]
