# Generated by Django 5.2.14 on 2026-08-31 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0082_founderlisting_creator_coin_amount_base_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundercartitem",
            name="payment_intent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="founder_cart_item",
                to="auctions.paymentintent",
            ),
        ),
        migrations.AddField(
            model_name="foundercartitem",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credits", "FANZ Credits"),
                    ("btc", "Bitcoin"),
                    ("doge", "Dogecoin"),
                    ("sui", "SUI"),
                ],
                default="credits",
                max_length=16,
            ),
        ),
    ]
