# Generated by Django 5.2.14 on 2026-08-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0083_foundercartitem_payment_intent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="settlement_reference",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="settlement_source",
            field=models.CharField(
                choices=[
                    ("btcpay", "BTCPay"),
                    ("sui", "Sui"),
                    ("internal", "Internal"),
                ],
                default="btcpay",
                max_length=16,
            ),
        ),
    ]
