# Generated by Django 5.2.14 on 2026-09-08 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0084_paymentintent_settlement_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderGiftClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=150)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("gift_message", models.TextField(blank=True)),
                ("suggested_sui_address", models.CharField(blank=True, max_length=128)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="founderownershipledger",
            name="founder_ledger_minimum_200_credit_conveyance",
        ),
        migrations.AlterField(
            model_name="founderownershipledger",
            name="transfer_type",
            field=models.CharField(
                choices=[
                    ("p2p_fixed", "P2P Fixed Price"),
                    ("p2p_blind", "P2P Blind Sale"),
                    ("minimum_conveyance", "Minimum Founder Conveyance"),
                    ("treasury_release", "FANZ Treasury Release"),
                    ("cb_redemption", "FANZ CB Redemption"),
                    ("gift_claim", "Founder Gift Claim"),
                ],
                default="minimum_conveyance",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="founderownershipledger",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("platform_fee_credits", 0),
                        ("sale_price_credits", 0),
                        ("seller_proceeds_credits", 0),
                        ("transfer_type", "gift_claim"),
                    ),
                    ("sale_price_credits__gte", 200),
                    _connector="OR",
                ),
                name="founder_ledger_valid_conveyance_value",
            ),
        ),
        migrations.AddField(
            model_name="foundergiftclaim",
            name="cart_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gift_claim",
                to="auctions.foundercartitem",
            ),
        ),
        migrations.AddField(
            model_name="foundergiftclaim",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claimed_founder_gifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foundergiftclaim",
            name="founder_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gift_claims",
                to="auctions.founderaccount",
            ),
        ),
        migrations.AddField(
            model_name="foundergiftclaim",
            name="purchaser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchased_founder_gifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
