# Generated by Django 5.2.14 on 2026-09-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0085_foundergiftclaim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("tip", "Tip"),
                    ("unlock", "Premium Unlock"),
                    ("purchase", "Purchase"),
                    ("credit_purchase", "Credit Purchase"),
                    ("commission", "Commission"),
                    ("bonus", "Bonus"),
                    ("game", "Game"),
                    ("ai_message", "AI Message"),
                ],
                max_length=20,
            ),
        ),
    ]
