# Generated by Django 5.2.14 on 2026-09-10 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0086_alter_wallettransaction_transaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_key", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "mode",
                    models.CharField(
                        choices=[("pay", "Pay"), ("spend", "Spend"), ("hold", "Hold")],
                        default="pay",
                        max_length=16,
                    ),
                ),
                (
                    "settlement_mode",
                    models.CharField(
                        choices=[
                            ("platform", "FANZ Platform"),
                            ("direct_seller", "Direct Seller"),
                        ],
                        default="platform",
                        max_length=24,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("fulfillment_type", models.CharField(max_length=64)),
                ("fulfillment_metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vending_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="vending_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_intents",
                to="auctions.vendingproduct",
            ),
        ),
    ]
