# Generated by Django 5.2.14 on 2026-09-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0087_vendingproduct_paymentintent_vending_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="SunsetCamCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_date", models.DateField()),
                (
                    "capture_type",
                    models.CharField(
                        choices=[
                            ("midnight", "Midnight"),
                            ("morning", "Morning"),
                            ("midday", "Midday"),
                            ("sunset", "Sunset"),
                        ],
                        max_length=16,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sunsetcam_captures",
                        to="auctions.feedpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-local_date", "-captured_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("local_date", "capture_type"),
                        name="unique_sunsetcam_capture_per_slot",
                    )
                ],
            },
        ),
    ]
