# Generated by Django 5.2.14 on 2026-09-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0088_sunsetcamcapture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="economyasset",
            name="founder_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="economy_asset",
                to="auctions.founderaccount",
            ),
        ),
    ]
