# Generated by Django 5.2.14 on 2026-09-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0089_alter_economyasset_founder_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sunsetcamcapture",
            name="capture_type",
            field=models.CharField(
                choices=[
                    ("midnight", "Midnight"),
                    ("morning", "Morning"),
                    ("midday", "Midday"),
                    ("sunset", "Sunset (legacy)"),
                    ("sunset_1", "Sunset 1"),
                    ("sunset_2", "Sunset 2"),
                    ("sunset_3", "Sunset 3"),
                    ("sunset_4", "Sunset 4"),
                ],
                max_length=16,
            ),
        ),
    ]
