# Generated by Django 5.2.14 on 2026-09-15 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0090_alter_sunsetcamcapture_capture_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorExecutionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custody_address", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("signed", "Signed"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "claimed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "claim_nonce",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tx_digest",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_execution_request",
                        to="auctions.economyassetdelivery",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
