# Generated by Django 5.2.14 on 2026-09-15 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0092_creatoredgeregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorEdgeAuthChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=128, unique=True)),
                ("message", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auth_challenges",
                        to="auctions.creatoredgeregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
