# Generated by Django 5.2.14 on 2026-09-22 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0093_creatoredgeauthchallenge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_key", models.CharField(max_length=160, unique=True)),
                ("source_path", models.TextField()),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("content", models.TextField(blank=True, default="", max_length=2000)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed_post",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_publication",
                        to="auctions.feedpost",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="schedpub_status_due_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("feed_post__isnull", False),
                                ("published_at__isnull", False),
                                ("status", "published"),
                            ),
                            models.Q(("status", "published"), _negated=True),
                            _connector="OR",
                        ),
                        name="schedpub_published_requires_post",
                    )
                ],
            },
        ),
    ]
