# Generated by Django 5.2.14 on 2026-09-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0094_scheduledpublication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorEdgePublicationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_key", models.CharField(max_length=160, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_edge_publication_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_receipts",
                        to="auctions.creatoredgeregistration",
                    ),
                ),
                (
                    "feed_post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_edge_publication_receipt",
                        to="auctions.feedpost",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
