# Generated by Django 5.2.14 on 2026-10-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0095_creatoredgepublicationreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedposttranslation",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for this language. Falls back to the original post image.",
                null=True,
                upload_to="feed/translations/",
            ),
        ),
    ]
