# Generated by Django 5.2.14 on 2026-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0097_feedpostlocalizationstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpostlocalizationstate",
            name="audited_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 fingerprint of post and translation text after a successful localization audit.",
                max_length=64,
            ),
        ),
    ]
